<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEmrfmk0\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEmrfmk0/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerEmrfmk0.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerEmrfmk0\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerEmrfmk0\appProdProjectContainer([
    'container.build_hash' => 'Emrfmk0',
    'container.build_id' => '693123df',
    'container.build_time' => 1669278463,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEmrfmk0');
