<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCrovht0\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCrovht0/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerCrovht0.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerCrovht0\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerCrovht0\appProdProjectContainer([
    'container.build_hash' => 'Crovht0',
    'container.build_id' => '765cc814',
    'container.build_time' => 1665431416,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCrovht0');
