<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQjjvxzs\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQjjvxzs/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerQjjvxzs.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerQjjvxzs\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerQjjvxzs\appProdProjectContainer([
    'container.build_hash' => 'Qjjvxzs',
    'container.build_id' => '9d55bd63',
    'container.build_time' => 1666815939,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQjjvxzs');
