<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZru1eka\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZru1eka/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerZru1eka.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerZru1eka\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerZru1eka\appDevDebugProjectContainer([
    'container.build_hash' => 'Zru1eka',
    'container.build_id' => 'ea870236',
    'container.build_time' => 1666725722,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZru1eka');
