<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGsmltnu\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGsmltnu/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerGsmltnu.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerGsmltnu\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerGsmltnu\appDevDebugProjectContainer([
    'container.build_hash' => 'Gsmltnu',
    'container.build_id' => '49d97a7c',
    'container.build_time' => 1666817478,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGsmltnu');
